"""Local LLM Triage Layer (Phase 6A & 6A.1)."""

try:
    import aiohttp
    import pydantic
except ImportError as err:
    raise ImportError("Dependencies for [llm] extra (aiohttp, pydantic) are not installed.") from err

from local_anonymizer.llm.schema import (
    TriageAction,
    TriageConfidence,
    TriageItem,
    TriageKeepItem,
    TriageRecategorizeItem,
    TriageDiscardItem,
    TriageEnvelope,
    validate_batch_response,
    extract_json_from_llm_response,
    validate_model_name,
    CatalogSuitability,
    CatalogPhaseEvaluation,
    CatalogModelEntry,
    CatalogSchema,
    DiscoveryStatus,
    DiscoveryResult,
    PsModelInfo,
    SetupState,
)
from local_anonymizer.llm.provider import (
    LlmProvider,
    LocalApiProvider,
    validate_loopback_url,
    derive_ollama_base_url,
    fetch_ollama_models,
    fetch_generic_models,
    preload_ollama_model,
    test_generic_connection,
    verify_ollama_model_running,
    parse_iso_expiry,
    DEFAULT_OLLAMA_KEEP_ALIVE,
    DEFAULT_CONNECT_TIMEOUT,
    DEFAULT_READ_TIMEOUT,
    DEFAULT_TOTAL_TIMEOUT,
    DEFAULT_PRELOAD_TIMEOUT,
    MAX_RESPONSE_BYTES,
    PROVIDER_TYPE_OLLAMA,
    PROVIDER_TYPE_GENERIC,
)
from local_anonymizer.llm.catalog import (
    CatalogError,
    load_catalog,
    find_catalog_entry,
    get_model_suitability_badge,
)
from local_anonymizer.llm.batching import TriageBatch, prepare_triage_batches
from local_anonymizer.llm.apply_service import (
    ApplyCommand,
    ApplyService,
    compute_triage_snapshot,
    normalize_entity_type,
    check_mutation_allowed,
    CANONICAL_APP_ENTITY_TYPES,
    ENTITY_TYPE_ALIASES,
)

__all__ = [
    "TriageAction",
    "TriageConfidence",
    "TriageItem",
    "TriageKeepItem",
    "TriageRecategorizeItem",
    "TriageDiscardItem",
    "TriageEnvelope",
    "validate_batch_response",
    "extract_json_from_llm_response",
    "validate_model_name",
    "CatalogSuitability",
    "CatalogPhaseEvaluation",
    "CatalogModelEntry",
    "CatalogSchema",
    "DiscoveryStatus",
    "DiscoveryResult",
    "PsModelInfo",
    "SetupState",
    "LlmProvider",
    "LocalApiProvider",
    "validate_loopback_url",
    "derive_ollama_base_url",
    "fetch_ollama_models",
    "fetch_generic_models",
    "preload_ollama_model",
    "test_generic_connection",
    "DEFAULT_OLLAMA_KEEP_ALIVE",
    "DEFAULT_CONNECT_TIMEOUT",
    "DEFAULT_READ_TIMEOUT",
    "DEFAULT_TOTAL_TIMEOUT",
    "DEFAULT_PRELOAD_TIMEOUT",
    "MAX_RESPONSE_BYTES",
    "PROVIDER_TYPE_OLLAMA",
    "PROVIDER_TYPE_GENERIC",
    "CatalogError",
    "load_catalog",
    "find_catalog_entry",
    "get_model_suitability_badge",
    "TriageBatch",
    "prepare_triage_batches",
    "ApplyCommand",
    "ApplyService",
    "compute_triage_snapshot",
    "normalize_entity_type",
    "check_mutation_allowed",
    "CANONICAL_APP_ENTITY_TYPES",
    "ENTITY_TYPE_ALIASES",
]
